[정수론] 3월 5일
Altu-Bitu-6/Altu-Bitu-JeongJisoo pull request #3
Opened 2024-03-05 09:17 UTC by JisooJudy

## 인적사항
학번: 2176352
이름: 정지수

## 과제제출
기존제출: 1735, 2840, 6588

2024-03-08 06:43 UTC, chae-jpg requested changes
**[정수론 이론 코드리뷰 완료]**

1735(P3), 6588(P1)
지수님 안녕하세요! 코드 리뷰 완료되었습니다👍
현재 6588번 문제가 백준 상으로 에러 판정이 나오고 있습니다 😢 
리뷰 확인하신 후 수정하셔서 다시 리뷰어 호출 부탁드립니다!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-03-08 06:43 UTC, chae-jpg commented on 03_정수론/1735.cpp
> +int gcdIter(int b, int d){
유클리드 호제법을 잘 구현해주셨어요!

2024-03-08 06:43 UTC, chae-jpg commented on 03_정수론/1735.cpp
> +    top = a*d + b*c;
연산 후 분자와 분모를 각각 잘 구해주셨네요!

2024-03-08 06:43 UTC, chae-jpg commented on 03_정수론/1735.cpp
> +    top /= gcd;
기약분수가 되기 위한 조건을 이용해서 새로운 분자와 분모를 잘 찾아주셨네요!

2024-03-08 06:43 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +vector<int> prime(int n){
에라토스테네스의 체를 이용해서 소수를 잘 판정해주셨네요!

2024-03-08 06:43 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +    vector<int> fac = prime(n);
P1
현재 이 부분으로 인해서 백준 상으로 런타임 에러가 나고 있습니다 😢 
지금 n이 초기화되지 않은 상태에서 n을 이용해 배열의 크기를 정의하고 있죠? 어떻게 수정하면 오류를 고칠 수 있을까요?  

그리고 추가로 bool이 int에 비해서 크기가 3바이트나 더 작기 때문에 정수 배열을 써야하는 특별한 이유가 없다면 bool 배열을 사용하는 편이 메모리상 더 효율적입니다!

2024-03-08 06:43 UTC, chae-jpg commented on 03_정수론/6588.cpp
> +            }
합이 두 소수로 이루어진 경우를 구해둔 소수 여부 배열을 이용해서 잘 찾아주셨어요!

2024-03-08 07:25 UTC, kimhj010502 reviewed
**[정수론 구현 문제 코드 리뷰 완료]**

2840(P2)

지수님 안녕하세요!
과제하시느라 수고 많으셨습니다!! 어려운 문제인데도 잘 풀어주셨네요! 🥰 
코드에 대한 간단한 주석이 있으면 더 좋을 것 같아요. 😎
몇 가지 사소한 코멘트 드렸습니다.
궁금한 점이 있으면 리뷰어를 호출해주세요!

2024-03-08 07:25 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +int main() {
P2. 모든 연산을 main 함수에서 해주었네요~ 알튜비튜에서는 함수로 구현할 수 있는 부분은 최대한 함수를 따로 정의해서 사용하는 것을 권장하고 있어요!

2024-03-08 07:25 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +       }
`index = (index - s % n + n) % n;` 한 줄로 구현할 수 있습니다!

2024-03-08 07:25 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +       else wheel[index] = word;
조건문을 사용할 때 중괄호가 없으면 나중에 수정할 일이 있을 때 불편할 일이 생길 수 있어요 한줄짜리 조건문도 중괄호를 사용해주세요!

2024-03-08 07:25 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +   }
하나씩 확인하면서 알파벳의 중복을 체크해주셨네요~ 이 방법도 좋지만 wheel의 크기가 커지면 시간 초과가 발생할 수 있으니 알파벳의 중복을 체크하는 vector를 만들어서 관리하는 샘플 답안 코드를 참고해주세요!

2024-03-10 13:39 UTC, chae-jpg requested changes
안녕하세요 효주님! 코드에서 수정 필요한 부분이 있어 다시 코멘트 드립니다 😢
리뷰 확인 후 수정하신 뒤, 다시 리뷰어를 호출해주세요!

2024-03-11 04:43 UTC, JisooJudy commented on 03_정수론/6588.cpp
> +    vector<int> fac = prime(n);
수정했습니다 확인 부탁드리겠습니다! 리뷰 확인이 늦어서 죄송합니다!

2024-03-13 02:38 UTC, chae-jpg approved these changes
**[정수론 이론 코드리뷰 완료]**

안녕하세요 지수님! 코드 수정 확인되었습니다. 수고하셨습니다~👍

2024-03-19 03:53 UTC, merged